### ISSUE TITLE
文件名特殊字符

### ISSUE THREAD

**Issue by XyyF** [wizaaard/wizard#27]
![e6e75c9fac382ff39ede757531c121d](https://user-images.githubusercontent.com/29220339/101149777-5a027880-365a-11eb-886b-5c8afba78821.png)
![09c8869e6f79aa54e83b1ed991cabc2](https://user-images.githubusercontent.com/29220339/101149785-5c64d280-365a-11eb-8f76-9aa83cba8f5b.png)

在windows下特殊字符无法识别处理

**Comment by mistricky** [comment]
An error caused by inconsistent representation of the first char on a different platform (Mac OS & Windows)

**Comment by youncccat** [comment]
An error caused by inconsistent representation of the first char on a different platform (Mac OS & Windows)
