### ISSUE TITLE
git commit msg

### ISSUE THREAD

**Issue by XyyF** [wizaaard/wizard#30]
添加

feat: msg
fix: msg

这种形式的msg内容兼容

**Comment by mistricky** [comment]
[commitlint](https://github.com/conventional-changelog/commitlint) lint commit message

**Comment by XyyF** [comment]
功能点：检验git commit格式

可以通过learn跑一个bin脚本命令子包，个人觉得没必要上commitlint

**Comment by mistricky** [comment]
@XyyF 这跟 lerna 没啥关系吧，commitlint 的考虑在下面几个点:

1. 如果直接用现在的 shell 来跑，意味着跟规则和校验逻辑耦合，修改规则需要改动源代码，commitlint 在于把规则和校验拆开，通过 config 来驱动配置，修改规则只用修改配置文件。
2. commitlint 做了平台无关性的处理，这里只有用平台无关的语言来抹平这个差异（Node Python etc.）这是没有必要的操作

**Comment by mistricky** [comment]
> 功能点：检验git commit格式
> 
> 可以通过learn跑一个bin脚本命令子包，个人觉得没必要上commitlint

至于 increment lint 和 hook 其实是与 commitlint 没有关系的，commitlint 只负责校验，而 hook 可以用 husky 或者其他东西来自动搭上 git hook

**Comment by XyyF** [comment]
commit规则是在最初规定的规范，规范不变，基本不会修改代码

learn来做bin脚本，commitlint也是base on node，我觉得没什么差别

**Comment by mistricky** [comment]
@XyyF  1. 规范是会增加的，在实践的过程中发现有不合场景或者考虑欠佳的地方是会变动的，规范是大家都遵守的一个约定，而不是不会变动的教条
2. 同上，没有什么差别，在两者的某一个 prop 都差不多的情况下，应该比较其他的 prop，所以是没有必要的操作

**Comment by XyyF** [comment]
commitlint规则为 <types>(scope): docs
和现有规则 [Types] docs，格式不兼容

**Comment by mistricky** [comment]
@XyyF https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md

**Comment by XyyF** [comment]
commitlint无法支持以下格式

[Type] subject

**Comment by XyyF** [comment]
commitlint源码：

1. 头部匹配规则为：
headerPattern: /^(\w*)(?:\((.*)\))?: (.*)$/
匹配 type(scope?): subject
headerPattern无法通过commitlint外部配置修改

**Comment by mistricky** [comment]
看了下，确实没有提供 custom rules 的接口，其实可以 hack 一下它那个规则，用 `commitlint-plugin-function-rules` 支持下 message 就行。

但是好折腾，还是自己写吧～

**Comment by XyyF** [comment]
# 目录结构
```js
- packages
  - wizard-cli
    - package.json
    - ...
```

# 目标
提供 wizard-cli 脚本工具，承载未来的一些功能

# 技术

- 开发中，通过 lerna 管理packages的方式，将 wizard-cli 加载到node_modules中，可以在package.json中设置命令运行
```js
  "husky": {
    "hooks": {
      "commit-msg": "wizard-cli commit-lint"
    }
  }
```
- 发布 npm package，可以直接在命名行中使用 wizard-cli 命令

**Comment by mistricky** [comment]
Close this discussion, it geted move to https://github.com/wizardoc/wizard/issues/42
